RKK/urls.py
# coding: utf-8
from django.conf.urls import patterns, include, url

from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'RKK.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(ur'^admin/', include(admin.site.urls)),
    url(ur'^Среда-МКС/', include('app.urls')),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/forms.py
# coding: utf-8
from django import forms
from .widgets import *
from .models import CM


class UploadFileForm(forms.Form):
    raw_files = forms.FileField(widget=MultiFileInput)


class Plot(forms.Form):
    labelX = forms.CharField()
    labelY = forms.CharField()
    color = forms.CharField()
    marker = forms.CharField()
    legend = forms.CharField()
    grid = forms.IntegerField()
    interpolation = forms.CharField()
    step = forms.IntegerField()
    linewidth = forms.FloatField()

class SelectFiles(forms.Form):
    date = forms.DateField()
    files = forms.CharField()

app/templates/draw_plot.html
{% extends 'base.html' %}
{% block content %}
<form method="post" class="form-horizontal col-lg-8 col-lg-offset-2">
{% csrf_token %}
    <fieldset>
        <legend>Построение графика</legend>
        <div class="form-group">
          <label for="id_date" class="col-lg-2 col-lg-offset-2 control-label">Выберите дату</label>
          <div class="col-lg-4">
            <select class="form-control" id="id_date" name="date" disabled>
              <option>{{ date }}</option>
            </select>
            <br>
          </div>
        </div>
        <div class="form-group">
          <label for="id_files" class="col-lg-2 col-lg-offset-2 control-label">Выберите файл</label>
          <div class="col-lg-4">
            <select class="form-control" id="id_files" name="files" disabled>
              <option>{{ param }}</option>
            </select>
            <br>
          </div>
              <a href="/media/{{ file }}" class="btn btn-info btn-sm">Файл</a>
        </div>
        <div class="form-group">
            <label for="id_labelX" class="col-lg-2 col-lg-offset-2 control-label">Ось Х</label>
            <div class="col-lg-4">
                <select class="form-control" id="id_labelX" name="labelX">
                    {% for label in labels %}
                    <option>{{ label }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="form-group">
            <label for="id_labelY" class="col-lg-2 col-lg-offset-2 control-label">Ось Y</label>
            <div class="col-lg-4">
                <select class="form-control" id="id_labelY" name="labelY">
                    {% for label in labels %}
                    {% if label != 'Время' %}
                    <option>{{ label }}</option>
                    {% endif %}
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="form-group">
            <label for="id_color" class="col-lg-2 col-lg-offset-2 control-label">Выберите цвет</label>
            <div class="col-lg-4">
                <select class="form-control" id="id_color" name="color">
                  <option>k: Черный</option>
                  <option class="text-primary">b: Синий</option>
                  <option class="text-success">g: Зеленый</option>
                  <option class="text-danger">r: Красный</option>
                  <option class="text-info">c: Голубой</option>
                  <option class="text-warning">y: Желтый</option>
                </select>
            </div>
        </div>
         <div class="form-group">
            <label for="id_marker" class="col-lg-2 col-lg-offset-2 control-label">Выберите маркер</label>
            <div class="col-lg-4">
                <select class="form-control" id="id_marker" name="marker">
                    {% autoescape off %}
                    <option>'None': Без маркера</option>
                    <option>'*': Звезда</option>
                    <option>'x': Крест</option>
                    <option>'+': Плюс</option>
                    <option>'.': Точка</option>
                    <option>',': Пиксель</option>
                    <option>'o': Круг</option>
                    <option>'v': Треугольник вниз</option>
                    <option>'^': Треугольник вверх</option>
                    <option>'<': Треугольник влево</option>
                    <option>'>': Треугольник вправо</option>
                    <option>'8': Восьмиугольник</option>
                    <option>'s': Квадрат</option>
                    <option>'p': Пятиугольник</option>
                    <option>'|': Вертикальная линия</option>
                    <option>'_': Горизонтальная линия</option>
                    {% endautoescape %}
                </select>
            </div>
         </div>
         <div class="form-group">
            <label for="id_linewidth" class="col-lg-4 control-label">Введите толщину линии</label>
            <div class="col-lg-4">
                <input type="number" class="form-control" name="linewidth" id="id_linewidth" placeholder="Дробная часть отделяется точкой">
            </div>
        </div>
        <div class="form-group">
            <label class="col-lg-2 col-lg-offset-2 control-label">Включить легенду?</label>
            <div class="col-lg-4">
              <div class="radio-inline">
                <label>
                  <input type="radio" name="legend" id="id_legend1" value="True">
                  Да
                </label>
              </div>
              <div class="radio-inline">
                <label>
                  <input type="radio" name="legend" id="id_legend2" value="False" checked="">
                    Нет
                </label>
              </div>
            </div>
        </div>
        <div class="form-group">
            <label for="id_grid" class="col-lg-2 col-lg-offset-2 control-label">Шаг сетки</label>
            <div class="col-lg-4">
                <input type="number" name="grid" class="form-control" id="id_grid" placeholder="Минуты">
            </div>
        </div>

        <div class="form-group">
            <label class="col-lg-3 col-lg-offset-1 control-label">Использовать интерполяцию?</label>
            <div class="col-lg-4">
              <div class="radio-inline">
                <label>
                  <input type="radio" name="interpolation" id="id_interpolation1" value="True" checked="">
                  Да
                </label>
              </div>
              <div class="radio-inline">
                <label>
                  <input type="radio" name="interpolation" id="id_interpolation2" value="False">
                    Нет
                </label>
              </div>
            </div>
        </div>
        <div class="form-group">
            <label for="id_step" class="col-lg-4 control-label">По скольким точкам строить график?</label>
            <div class="col-lg-4">
                <input type="number" class="form-control" name="step" id="id_step" placeholder="Введите количество точек">
            </div>
        </div>
        <div class="form-group">
          <div class="col-lg-10 col-lg-offset-6">
            <button type="submit" class="btn btn-primary">Построить</button>
          </div>
        </div>
    </fieldset>
</form>
{% endblock %}

app/templates/form.html
{% extends 'base.html' %}
{% block content %}
<form class="form-horizontal">
  <fieldset>
    <legend>Legend</legend>
    <div class="form-group">
      <label for="inputEmail" class="col-lg-2 control-label">Email</label>
      <div class="col-lg-10">
        <input type="text" class="form-control" id="inputEmail" placeholder="Email">
      </div>
    </div>
    <div class="form-group">
      <label for="inputPassword" class="col-lg-2 control-label">Password</label>
      <div class="col-lg-10">
        <input type="password" class="form-control" id="inputPassword" placeholder="Password">
        <div class="checkbox">
          <label>
            <input type="checkbox"> Checkbox
          </label>
        </div>
      </div>
    </div>
    <div class="form-group">
      <label for="textArea" class="col-lg-2 control-label">Textarea</label>
      <div class="col-lg-10">
        <textarea class="form-control" rows="3" id="textArea"></textarea>
        <span class="help-block">A longer block of help text that breaks onto a new line and may extend beyond one line.</span>
      </div>
    </div>
    <div class="form-group">
      <label class="col-lg-2 control-label">Radios</label>
      <div class="col-lg-10">
        <div class="radio">
          <label>
            <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1" checked="">
            Option one is this
          </label>
        </div>
        <div class="radio">
          <label>
            <input type="radio" name="optionsRadios" id="optionsRadios2" value="option2">
            Option two can be something else
          </label>
        </div>
      </div>
    </div>
    <div class="form-group">
      <label for="select" class="col-lg-2 control-label">Selects</label>
      <div class="col-lg-10">
        <select class="form-control" id="select">
          <option>1</option>
          <option>2</option>
          <option>3</option>
          <option>4</option>
          <option>5</option>
        </select>
        <br>
        <select multiple="" class="form-control">
          <option>1</option>
          <option>2</option>
          <option>3</option>
          <option>4</option>
          <option>5</option>
        </select>
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <button class="btn btn-default">Cancel</button>
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </div>
  </fieldset>
</form>
{% endblock %}

app/templates/list_db.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<div class="col-lg-8 col-lg-offset-2">
    {% for cm in CMs %}
    <div class="row">
    <div id="carousel-{{ cm.date|date:"d-m-Y" }}" class="carousel slide" data-ride="carousel" data-interval="10000">
        <!-- Индикаторы -->
        <ol class="carousel-indicators">
          <li data-target="#mod" data-slide-to="0" class="active"></li>
          <li data-target="#cmx" data-slide-to="1"></li>
          <li data-target="#cmy" data-slide-to="2"></li>
          <li data-target="#cmz" data-slide-to="3"></li>
        </ol>
        <!-- Содержимое слайдера (Обёртка для слайдов)-->
        <div class="carousel-inner">
          <div class="item active" id="mod">
            <img src="/media/{{ cm.plot_mod }}" alt="Модуль">
          </div>
          <div class="item" id="cmx">
            <img src="/media/{{ cm.plot_cmx }}" alt="CMX">
          </div>
          <div class="item" id="cmy">
            <img src="/media/{{ cm.plot_cmy }}" alt="CMY">
          </div>
          <div class="item" id="cmz">
            <img src="/media/{{ cm.plot_cmz }}" alt="CMZ">
          </div>
        </div>
        <!-- Контролы -->
        <a class="left carousel-control" href="#carousel-{{ cm.date|date:"d-m-Y" }}" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left"></span>
        </a>
        <a class="right carousel-control" href="#carousel-{{ cm.date|date:"d-m-Y" }}" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
    </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

app/templates/object.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<div class="col-lg-8">
    <img src="/media/{{ cm.plot_mod }}" alt="Модуль">
    <img src="/media/{{ cm.plot_cmx }}" alt="CMX">
    <img src="/media/{{ cm.plot_cmy }}" alt="CMY">
    <img src="/media/{{ cm.plot_cmz }}" alt="CMZ">
</div>
{% endblock %}

app/templates/select_files.html
{% extends 'base.html' %}
{% block content %}
<form method="post" class="form-horizontal col-lg-8 col-lg-offset-2">
{% csrf_token %}
    <fieldset>
        <legend>Построение графика</legend>
        <div class="form-group">
          <label for="id_date" class="col-lg-2 col-lg-offset-2 control-label">Выберите дату</label>
          <div class="col-lg-4">
            <select class="form-control" id="id_date" name="date">
              {% for cm in CMs %}
                <option>{{ cm }}</option>
              {% endfor %}
            </select>
            <br>
          </div>

        </div>
        <div class="form-group">
          <label for="id_files" class="col-lg-2 col-lg-offset-2 control-label">Выберите файл</label>
          <div class="col-lg-4">
            <select class="form-control" id="id_files" name="files">
              <option>Магнитометры</option>
              <option>Кватернионы</option>
              <option>Угловые скорости</option>
            </select>
            <br>
          </div>
        </div>
        <div class="form-group">
          <div class="col-lg-10 col-lg-offset-2">
            <button type="submit" class="btn btn-primary">Выбрать</button>
          </div>
        </div>

    </fieldset>
</form>
{% endblock %}

app/templates/upload_result.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
  <div class="col-lg-12">
    {% if messages %}
      {% for message in messages %}
         {% if message.tags %}
            <div class="alert alert-dismissable alert-{{ message.tags }}">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <h4>Ошибка!</h4>
                <p>{{ message }}</p>
            </div>
         {% endif %}
      {% endfor %}
    {% else %}
        <div class="alert alert-dismissable alert-success">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <strong>Успешно!</strong>.
        </div>
    {% endif %}
  </div>
</div>
{% endblock %}